---
- hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Brew install or update preinstalled
    homebrew:
      name: "{{ item }}"
      state: present
    with_items:
      - jupyter

  - name: Brew cask install applications
    homebrew_cask:
      name: "{{ item }}"
      state: present
    with_items:
      - google-chrome
      - iterm2
      - intellij-idea
      - atom
      - spotify
      - 1password
      - zoomus
      - whatsapp

  - name: pip3 install virtualenv
    pip:
      name: virtualenv
      executable: pip3

  - name: Create projects directory
    file:
      path: ~/projects
